name: Radar de Notícias

on:
  schedule:
    - cron: '*/15 * * * *' # Roda a cada 15 minutos
  workflow_dispatch: # Permite rodar clicando num botão

jobs:
  rodar-radar:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Preparar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas
        run: pip install -r requirements.txt

      - name: Rodar o script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
